image: tuxity/docker-php5-composer

script:
  - composer install --no-dev --no-interaction
  - composer dump-autoload --optimize

deploy:
  ssh:
    target: ubuntu@ec2-52-20-239-124.compute-1.amazonaws.com:~/sheaker-back.tar
    artifacts:
      - .deploy
      - config
      - public/index.php
      - sql
      - src
      - vendor
      - composer.json
      - composer.lock
    cmd: mkdir sheaker-back; tar -xf sheaker-back.tar -C sheaker-back; cd sheaker-back; .deploy/remote.sh
    when:
      branch: master

notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    on_started: false
    on_success: true
    on_failure: true
