clone:
  depth: 20
  recursive: true
  submodule_update_remote: true

build:
  image: tuxity/drone-php5-composer
  pull: true
  commands:
    - composer install --no-interaction --no-dev --no-progress --optimize-autoloader

deploy:
  sftp:
    host: sheaker.com
    username: ubuntu
    destination_path: /tmp/sheaker
    files:
      - .deploy
      - config
      - public/index.php
      - sql
      - src
      - vendor
      - composer.json
      - composer.lock
    when:
      branch: master
  ssh:
    host: sheaker.com
    user: ubuntu
    commands:
      - /tmp/sheaker/.deploy/remote.sh
    when:
      branch: master

notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: notifications
    username: Drone
    template: >
      Build <https://drone.sheaker.com/{{ repo.full_name }}/{{ build.number }}|{{ repo.name }}#{{ truncate build.commit 7 }}> ({{ build.branch }}) by {{ build.author }} finished with a *{{ build.status }}* status in {{ duration build.started_at build.finished_at }}
